### ISSUE TITLE
feat: add dialog box to complaint button

### ISSUE THREAD

**Issue by Saravana200** [Broadway-Communications/Flutter-Application#12]
![Image](https://github.com/Broadway-Communications/Flutter-Application/assets/96806975/e472b774-b467-4ad8-93d2-3f23cb03c935)

**Comment by pratikiran** [comment]
Close was to tough in developing according to the design. So its removed in developing.

**Comment by pratikiran** [comment]
The description was not able to develop according to the design.


![Image](https://github.com/Broadway-Communications/Flutter-Application/assets/66823602/d7a66294-ed9b-4b94-82fc-f1363d7db56c)

**Comment by Saravana200** [comment]
![Image](https://github.com/Broadway-Communications/Flutter-Application/assets/96806975/b45d44cb-e995-47b6-b320-27563bd08349)



made some changes to the Complaint Dialog Box and added the close button

**Comment by pratikiran** [comment]
Thank you @Saravana200 for fixing...
