### ISSUE TITLE
feat: add different states for complaint card

### ISSUE THREAD

**Issue by pratikiran** [Broadway-Communications/Flutter-Application#21]
Add design screen shots here @Geethanjali2608

**Comment by Geethanjali2608** [comment]
![Image](https://github.com/Broadway-Communications/Flutter-Application/assets/96220572/f614e657-e525-4b78-830f-09ef32fe5502)

**Comment by pratikiran** [comment]
@Geethanjali2608 guide in change of color of different states!!

**Comment by pratikiran** [comment]
![Screenshot_20230728-163550.png](https://github.com/Broadway-Communications/Flutter-Application/assets/66823602/7c716eaa-0f50-4305-8808-5b53f5cc145a)

The text in rate button is too big for the button, keep it default @Saravana200
