### ISSUE TITLE
fix: menu bar icon state

### ISSUE THREAD

**Issue by pratikiran** [Broadway-Communications/Flutter-Application#4]
When sidebar without the icon button the state seems to be not changing!!

![Image](https://github.com/Broadway-Communications/Flutter-Application/assets/66823602/35d130b7-3144-4091-a148-2d459086de40)

![Image](https://github.com/Broadway-Communications/Flutter-Application/assets/66823602/902860a9-eead-4574-9f63-823ffbf81e65)

**Comment by pratikiran** [comment]
![Screenshot_20230728-161915.png](https://github.com/Broadway-Communications/Flutter-Application/assets/66823602/1ebf06f8-e477-4cd2-a419-dac87417cf2b)

The logout button design should match all other buttons in the app @Saravana200

**Comment by Geethanjali2608** [comment]
Sidebar is having totally diff design from other frames so I don't think logout button should should follow other button design@pratikiran
